
version: '3'
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
           MYSQL_ROOT_PASSWORD: example123
           MYSQL_DATABASE: mmdb
           #    volumes:
           #- ./mysql:/docker-entrypoint-initdb.d   
        ports:
          - 3306:3306   
